name: Github Actions Automation Task
# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  pull_request:
    branches: [ main ]
  push:
    branches: [feature1]

jobs:
  build:

    runs-on: windows-latest
    permissions:
       contents: read
       packages: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step1- Checkout master branch from GitHub  
        uses: actions/checkout@v2
        env:
          USER_ID: ${{secrets.USERNAME}}
          PWD: ${{secrets.PASSWD}}
          run: 
                echo USER_ID
         
        
      -  name: Step2- List the current directory
         run: ls
             
             
      - name: Step3 - List the files present in target folder
        run: |
          pwd
          ls
        
      - name: Step4 - copy all the files in another folder
        run: |
           $targetFolder ="package"
           echo "Package -$targetFolder"
           if(Test-Path -LiteralPath .\$targetFolder) {
               Remove-Item -LiteralPath .\$targetFolder -Force -Recurse
               echo "Remove $pwd\\$targetFolder"
           }
           New-Item -Path .\$targetFolder -ItemType Directory
           Copy-Item -Path .\src -destination .\$targetFolder -Recurse
           Copy-Item -Path .\file1 -destination .\$targetFolder -Recurse
           Copy-Item -Path .\GRS_BI_Reporting\*.dtsx* -destination .\$targetFolder\GRS_BI_Reporting -Recurse
           
           dir $pwd\$targetFolder
           dir $pwd\$targetFolder\src\game
           dir $pwd\$targetFolder\GRS_BI_Reporting\
           dir $pwd
     
