name: Github Actions Automation Task
# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  pull_request:
    branches: [ main ]
  push:
    branches: [feature1]

jobs:
  build:

    runs-on: windows-latest
    permissions:
       contents: read
       packages: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step1- Checkout master branch from GitHub  
        uses: actions/checkout@v2
        env:
          USER_ID: ${{secrets.USERNAME}}
          PWD: ${{secrets.PASSWD}}
          run: 
                echo USER_ID
         
        
      -  name: Step2- List the current directory
         run: ls
             
             
      - name: Step3 - List the files present in target folder
        run: |
          pwd
          ls
          
      - name: Step4.1 - list the contents
        run: |
            Get-ChildItem .\listfile
        
     
